# Generated by Django 2.0 on 2022-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=128, verbose_name='实例id')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('vpc_addr', models.GenericIPAddressField(verbose_name='内网ip')),
                ('status', models.CharField(max_length=32, verbose_name='主机状态')),
                ('regain', models.CharField(max_length=16, verbose_name='regain')),
                ('cpu_core', models.IntegerField(verbose_name='cpu核数')),
                ('mem_size', models.IntegerField(verbose_name='内存G')),
                ('disk_size', models.IntegerField(verbose_name='磁盘G')),
                ('os_type', models.CharField(max_length=16, verbose_name='操作系统类型')),
                ('tags', models.CharField(max_length=256, verbose_name='tag json字符传')),
                ('desc', models.CharField(max_length=128, verbose_name='主机描述1')),
                ('g', models.CharField(max_length=32, verbose_name='group')),
                ('p', models.CharField(max_length=32, verbose_name='project')),
                ('a', models.CharField(max_length=32, verbose_name='app')),
                ('field_md5', models.CharField(max_length=64, verbose_name='字段md5')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'ecs_info',
            },
        ),
        migrations.CreateModel(
            name='StreePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='服务树级别')),
                ('path', models.CharField(max_length=16, verbose_name='物化路径')),
                ('node_name', models.CharField(max_length=32, verbose_name='节点名称')),
            ],
            options={
                'db_table': 'stree_path',
            },
        ),
        migrations.AlterUniqueTogether(
            name='streepath',
            unique_together={('level', 'path', 'node_name')},
        ),
    ]
