# Generated by Django 2.0 on 2022-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecsinfo',
            name='desc',
            field=models.CharField(max_length=256, verbose_name='主机描述1'),
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='hostname',
            field=models.CharField(max_length=128, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='tags',
            field=models.CharField(max_length=512, verbose_name='tag json字符传'),
        ),
    ]
