# Generated by Django 2.0 on 2022-02-25 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0003_auto_20220224_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='变更信息')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'asset_record',
            },
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='desc',
            field=models.TextField(verbose_name='主机描述1'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='ecs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ao', to='cloud_cmdb.EcsInfo', verbose_name='ecs对象'),
        ),
    ]
