# Generated by Django 2.0 on 2022-02-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0005_assetrecord_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrecord',
            name='record_type',
            field=models.IntegerField(choices=[(0, 'create'), (1, 'delete'), (2, 'update')], default=0),
        ),
    ]
