# Generated by Django 2.0 on 2022-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0006_auto_20220225_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrecord',
            name='ecs',
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='resource_id',
            field=models.CharField(default='', max_length=128, verbose_name='实例id'),
        ),
    ]
