# Generated by Django 2.0 on 2022-03-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0007_auto_20220226_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regain', models.CharField(max_length=16, verbose_name='regain')),
                ('instance_id', models.CharField(db_index=True, max_length=128, verbose_name='资源id')),
                ('status', models.CharField(max_length=32, verbose_name='资源状态')),
                ('g', models.CharField(max_length=32, verbose_name='group')),
                ('p', models.CharField(max_length=32, verbose_name='project')),
                ('a', models.CharField(max_length=32, verbose_name='app')),
                ('field_md5', models.CharField(max_length=64, verbose_name='资源字段md5')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instance_type', models.CharField(max_length=32, verbose_name='db实例类型')),
                ('instance_net_type', models.CharField(max_length=32, verbose_name='内外网连接方式')),
                ('instance_work_type', models.CharField(max_length=32, verbose_name='实例网络类型')),
                ('engine', models.CharField(max_length=64, verbose_name='数据库类型')),
                ('engine_version', models.CharField(max_length=16, verbose_name='数据库版本')),
                ('zone_id', models.CharField(max_length=64, verbose_name='可用区id')),
                ('connection_mode', models.CharField(max_length=32, verbose_name='连接类型')),
                ('connection_str', models.CharField(max_length=256, verbose_name='连接uri')),
                ('lock_mode', models.CharField(max_length=32, verbose_name='实例锁定状态')),
            ],
            options={
                'db_table': 'rds_info',
            },
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='field_md5',
            field=models.CharField(max_length=64, verbose_name='资源字段md5'),
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='instance_id',
            field=models.CharField(db_index=True, max_length=128, verbose_name='资源id'),
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='status',
            field=models.CharField(max_length=32, verbose_name='资源状态'),
        ),
    ]
