# Generated by Django 2.0 on 2022-03-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0008_auto_20220301_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrecord',
            name='resource_type',
            field=models.IntegerField(choices=[(0, 'ecs'), (1, 'rds')], default=0),
        ),
    ]
