# Generated by Django 2.0 on 2022-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0009_assetrecord_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClbInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regain', models.CharField(max_length=16, verbose_name='regain')),
                ('instance_id', models.CharField(db_index=True, max_length=128, verbose_name='资源id')),
                ('status', models.CharField(max_length=32, verbose_name='资源状态')),
                ('zone_id', models.CharField(max_length=64, verbose_name='可用区id')),
                ('g', models.CharField(max_length=32, verbose_name='group')),
                ('p', models.CharField(max_length=32, verbose_name='project')),
                ('a', models.CharField(max_length=32, verbose_name='app')),
                ('field_md5', models.CharField(max_length=64, verbose_name='资源字段md5')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip_version', models.CharField(max_length=32, verbose_name='ip类型 ipv4/ipv6')),
                ('network_type', models.CharField(max_length=32, verbose_name='私网负载均衡实例的网络类型 vpc/classic')),
                ('band_with', models.IntegerField(verbose_name='监听的带宽峰值，单位Mbps')),
                ('tags', models.CharField(max_length=512, verbose_name='tag json字符传')),
                ('clb_name', models.CharField(max_length=64, verbose_name='clb实例名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='zone_id',
            field=models.CharField(default=1, max_length=64, verbose_name='可用区id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='desc',
            field=models.TextField(verbose_name='主机描述'),
        ),
        migrations.AlterField(
            model_name='rdsinfo',
            name='connection_mode',
            field=models.CharField(max_length=32, verbose_name='连接类型 单点/集群'),
        ),
        migrations.AlterField(
            model_name='rdsinfo',
            name='instance_type',
            field=models.CharField(max_length=32, verbose_name='db实例类型 主/从'),
        ),
    ]
