# Generated by Django 2.0 on 2022-03-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0010_auto_20220302_1627'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clbinfo',
            table='clb_info',
        ),
    ]
