# Generated by Django 2.0 on 2022-03-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0011_auto_20220302_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpcInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regain', models.CharField(max_length=16, verbose_name='regain')),
                ('instance_id', models.CharField(db_index=True, max_length=128, verbose_name='资源id')),
                ('status', models.CharField(max_length=32, verbose_name='资源状态')),
                ('zone_id', models.CharField(max_length=64, verbose_name='可用区id')),
                ('g', models.CharField(max_length=32, verbose_name='group')),
                ('p', models.CharField(max_length=32, verbose_name='project')),
                ('a', models.CharField(max_length=32, verbose_name='app')),
                ('field_md5', models.CharField(max_length=64, verbose_name='资源字段md5')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cidr_block', models.CharField(max_length=32, verbose_name='VPC的IPv4网段')),
                ('desc', models.CharField(max_length=256, verbose_name='Description')),
                ('owner_id', models.IntegerField(verbose_name='VPC所属的阿里云账号ID')),
                ('tags', models.CharField(max_length=512, verbose_name='tag json字符传')),
                ('vpc_name', models.CharField(max_length=64, verbose_name='实例名称')),
            ],
            options={
                'db_table': 'vpc_info',
            },
        ),
    ]
