# Generated by Django 2.0 on 2022-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0012_vpcinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpcinfo',
            name='owner_id',
            field=models.CharField(max_length=64, verbose_name='VPC所属的阿里云账号ID'),
        ),
    ]
