# Generated by Django 2.0 on 2022-03-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0013_auto_20220302_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regain', models.CharField(max_length=16, verbose_name='regain')),
                ('instance_id', models.CharField(db_index=True, max_length=128, verbose_name='资源id')),
                ('status', models.CharField(max_length=32, verbose_name='资源状态')),
                ('zone_id', models.CharField(max_length=64, verbose_name='可用区id')),
                ('g', models.CharField(max_length=32, verbose_name='group')),
                ('p', models.CharField(max_length=32, verbose_name='project')),
                ('a', models.CharField(max_length=32, verbose_name='app')),
                ('field_md5', models.CharField(max_length=64, verbose_name='资源字段md5')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ssl_protocol', models.CharField(max_length=16, verbose_name='是否开启ssl')),
                ('desc', models.CharField(max_length=256, verbose_name='Description')),
                ('cname', models.CharField(max_length=128, verbose_name='cname')),
                ('domain_name', models.CharField(max_length=128, verbose_name='加速域名')),
                ('cdn_type', models.CharField(max_length=64, verbose_name='加速业务类型 web/download/video')),
                ('source_type', models.CharField(max_length=64, verbose_name='源站类型')),
                ('source_content', models.CharField(max_length=64, verbose_name='源站地址')),
                ('source_port', models.CharField(max_length=64, verbose_name='源站地端口')),
            ],
            options={
                'db_table': 'cdn_info',
            },
        ),
    ]
