# Generated by Django 2.0 on 2022-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_cmdb', '0014_cdninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdninfo',
            name='coverage',
            field=models.CharField(default='', max_length=16, verbose_name='加速区域 domestic：仅中国内地/global：全球/overseas：全球（不包含中国内地)'),
            preserve_default=False,
        ),
    ]
